# Production values for currency-converter
replicaCount: 3

image:
  repository: your-registry/currency-converter
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.company.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: currency-converter-tls
      hosts:
        - api.company.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  logLevel: "warn"
  cacheTimeout: 3600
  binanceApiTimeout: 30

redis:
  enabled: true
  host: "redis-cluster"
  port: 6379

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s